### ISSUE TITLE
[FEAT] Comparison for different users or service accounts

### ISSUE THREAD

**Issue by piotrminkina** [corneliusweig/rakkess#145]
Hello,

Firstly thanks for great app! Definitely useful at work!

Is it possible to present a comparison of permissions between different users or service accounts? In the attached image I present the visual aspect of such a comparison. I normally take a few screenshots and then glue them together in GIMP to get this effect.

![rakkess-preview-demo](https://user-images.githubusercontent.com/2574153/122177128-9b83a400-ce85-11eb-9577-60801258308c.png)

Example calls that this feature would do:
* compare different users: `rakkess --namespace ...-test --as appadmin --as view --verbs ...`
* compare different contexts: `rakkess --namespace ...-test --context ctx-appadmin-test-cluster --context ctx-view-test-cluster  --verbs ...`
* mixed comparison: `rakkess --namespace ...-test --as appadmin --sa sa-view --verbs ...`

Regards
Piotr Minkina

**Comment by corneliusweig** [comment]
Hi Piotr, this is a nice idea. I tried whether `wdiff` would give acceptable results, but it doesn't, because it messes up the table format. So it is not a task that can be done easily by combining existing tools.

For this to work, I need to restructure the code somewhat. I would do many things differently today, and I want the code to be more maintainable long-term.

**Comment by corneliusweig** [comment]
How about this format (with colors):

```
$ rakkess diff -n kube-system --sa=coredns sa=attachdetach-controller
NAME                    LIST  CREATE  UPDATE  DELETE
endpoints               ◀                     
events                        ▶       ▶       
events.events.k8s.io          ▶       ▶       
persistentvolumeclaims  ▶                     
services                ◀
```

Left will be the original access settings (here SA coredns), right is the patched one (here SA attachdetach-controller).

WDYT?

**Comment by piotrminkina** [comment]
Hello @corneliusweig 

Thanks for your interest in my proposal, I see a lot of work being done here. Unfortunately, I do not understand what the triangles and blanks mean. Maybe the colours you write about would explain something more, but no any colors with your example :)

Regards

**Comment by corneliusweig** [comment]
The arrows are supposed to indicate if a a given verb is allowed for the resource. For example
<empty> same for both configs
◀  The original config can access, but not the modified one
▶  The modified config can access, but not the original one

The idea is to highlight the diff between the two configs.

---

However, your reaction tells me that the given CLI does not work. I think a better syntax is

    rakkess diff --left=--sa=coredns --right=--sa=attachdetach-controller
