### ISSUE TITLE
Install failure via krew 

### ISSUE THREAD

**Issue by mg03** [corneliusweig/rakkess#41]
**Expected behavior**
Successful install

**Actual behavior**
kubectl krew install access_matrix
Updated the local copy of plugin index.
F1106 09:56:43.917989   62690 root.go:58] failed to load plugin "access_matrix" from the index: open /Users/mgarda/.krew/index/plugins/access_matrix.yaml: no such file or directory

**Steps To Reproduce**
Run:
kubectl krew install access_matrix

**Context:**
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}

**Additional context**

**Comment by corneliusweig** [comment]
Hi @mg03, I think it should read
```
kubectl krew install access-matrix
```
Mind the dash instead of the underscore.

**Comment by mg03** [comment]
@corneliusweig : that worked , thank you
