### ISSUE TITLE
Installation with Curl is failing "not in gzip format"

### ISSUE THREAD

**Issue by Aracki** [corneliusweig/rakkess#46]
When trying to install rakkess via curl with:
```
curl -Lo rakkess.gz https://github.com/corneliusweig/rakkess/releases/download/v0.4.2/rakkess-darwin-amd64.gz && \
  gunzip rakkess.gz && chmod +x rakkess && mv rakkess $GOPATH/bin/
```

I keep getting:
> gunzip: rakkess.gz: not in gzip format

**Comment by corneliusweig** [comment]
Woops.. I changed the release assets and forgot to adapt the manual install instructions. Thanks for reporting this!

Have you also considered installing via [krew](krew.dev)? The install process is covered via CI jobs there and should never break :wink:

**Comment by Aracki** [comment]
Have my own `krew` issue running it via `fish` shell. I am using rakkess already, but would like to have binary also 👍 Thanks
