### ISSUE TITLE
`rakkess version` is not printing version information

### ISSUE THREAD

**Issue by d2iq-shadowbq** [corneliusweig/rakkess#52]
**Expected behavior**
rakkess version
(version is printed)

**Actual behavior**
a blank line is printed

**Steps To Reproduce**
1. Steps to set up a minimal example demonstrating the error (including service accounts or similar)

with no cluster connected, but context defined, run `rakkess version`

2. What command was used

version

3. Run with option `-v debug` to show extra logging.

```shell
rakkess version -v debug
DEBU[0000] Set log-level to debug                       

```
**Context:**
Please include the full version information: `rakkess version --full`

The downloaded version was v0.4.3 Darwin amd64

```shell
rakkess version --full
rakkess:    
platform:   darwin/amd64
git commit: 
build date: 
go version: go1.13.7
compiler:   gc
```

**Additional context**

**Comment by corneliusweig** [comment]
Whoops.. thanks for reporting. Looks like I messed up my build when I renamed the version package.
