### ISSUE TITLE
oidc support

### ISSUE THREAD

**Issue by jaxxstorm** [corneliusweig/rakkess#7]
Firstly, this is an amazing tool!

Unfortunately, we use oidc via dex for authentication. Is there any way we could make the `--as` function work with that?

**Comment by corneliusweig** [comment]
Glad you like it :)

First off: what version are you using? v0.1.0 didn't properly support authentication plugins. There is a bugfix version v0.1.1 which does. You can check with `rakkess version --full`.

If you are using v0.1.0:
I don't know oidc and dex well enough. Does `kubectl` support that? At least I couldn't find any imports specific to dex in its codebase (such as `github.com/dexidp/dex`). Are there specific preparations to use oidc with dex?

**Comment by corneliusweig** [comment]
@jaxxstorm Can you tell me what version you were using? (See above comment for details)

**Comment by jaxxstorm** [comment]
hey sorry, not had time to look into this further to answers your questions, will try this week

**Comment by corneliusweig** [comment]
Hi @jaxxstorm, any update?

**Comment by corneliusweig** [comment]
Hi @jaxxstorm, I would really like to resolve this issue but I need more information.

**Comment by jaxxstorm** [comment]
This isn't a rakkess problem, it's a Kubernetes problem, so I'll close this, Sorry for the delay.

**Comment by corneliusweig** [comment]
Hey no problem. Thanks for investigating!
