### ISSUE TITLE
0.4.5 darwin archive is empty

### ISSUE THREAD

**Issue by nomeelnoj** [corneliusweig/rakkess#81]
**Expected behavior**
Downloading the darwin zip from https://github.com/corneliusweig/rakkess/releases/tag/v0.4.5 and extracting should result in a binary file

**Actual behavior**
Binary file is missing, only the LICENSE rile is present

**Steps To Reproduce**

1. curl the binary from https://github.com/corneliusweig/rakkess/releases/download/v0.4.5/access-matrix-amd64-darwin.tar.gz
2. `tar xvf <binary>
3. `ls` shows only LICENSE

**Context:**
Downloading and doing the same with 0.4.4 seems to still work properly.

**Additional context**
This is also affecting the install from `krew` as krew only supports the latest version.

**Comment by corneliusweig** [comment]
When I download the tarball, I see the following files in the archive:

```
$ tar tf access-matrix-amd64-darwin.tar.gz
LICENSE
access-matrix-amd64-darwin
```

Krew even has an install check that ensures all copied files are present in the tarball. I'm trying to understand what is going on here. I did start to compress binaries with `upx` starting with 0.4.5, but you should at least _see_ the file in the tarball.

**Comment by nomeelnoj** [comment]
i think you responded via slack--something weird going on here for sure. Ill try to get to the bottom of it and post back.  Sorry for the pebcak

**Comment by corneliusweig** [comment]
As discussed via slack it turned out to be an anti-virus software issue.
